import { Toaster } from 'sonner';
import './globals.css'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="min-h-screen dark">
            <body className="background min-h-screen flex flex-col items-center">
                {children}
                <Toaster />
            </body>
        </html>
    );
}
